import React from "react";
import Logo from "../../images/client_logos/petra-logo.png";

const PetraContent = () => {
    return (
        <>
            <div style={{justifyContent: "center", alignItems: "center", width: "100%", display: "flex"}}>
                <img src={Logo} alt="Petra Logo" style={{ width: "60%", height: "auto", paddingTop: "8px" }} decoding="async" loading="lazy"/>
            </div>
            <p>As Studio Wino we had designed a new brand identity system and updated packaging for the Istanbul based Petra Roasting Co.</p>
            <p style={{ paddingTop: "8px" }}>Coffee is not just coffee. It is either ones favorite routine in the morning or that 10-20 mins “me-time” that you get to enjoy with a product that has traveled maybe thousand miles to be in your palm or your kitchen counter. That is the driving idea we always fell back on when we were designing these packages. </p>
            <p style={{ paddingTop: "8px" }}>Merging every case we face throughout our research process, historic awareness and brand perception, the design approach in Petra Roasting Co. coffee packages feeds from ‘Bauhaus Art Movement’ representing the belief that a new life will be designed and identified as the era of modernization.</p>
            <p style={{ paddingTop: "8px" }}>With the knowledge that every single package we distribute is a strong marketing instrument, we reworked this daily used product at material and sizing process in company with the cost analysis for the maximum comfort of the consumer. By eliminating probable storing difficulties we may face in the course of daily use, we refused any aesthetic deformations in any ground we touched our consumer besides designing a better consumer experience, and we targeted to last long.</p>
            <p style={{ paddingTop: "8px" }}>We shaped the paper we chose as the material with sizes to minimize spilling by shaking rather than the boxes shaped with focuses of ‘stacking’ and ‘transportability’. As a result, besides gaining the ability to be piled double row we presented our consumer a more comfortable experience during and after the usage. </p>
            <p style={{ paddingTop: "8px" }}>Our main purpose here was to take the coffee beans reaching us from different countries with different tastes to the images that the consumer can easily remember (color-coding) thus increase the awareness to the coffee and present a more conscious shopping experience. While determining the colors we studied on the color palettes of the brands and products that established an emotional bond with the society from past to present. We tried to understand the color combinations we faced, dominant preferences and how the spaces were used. Along with our primary colors we determined the assistant colors and the exact point to use color by being influenced from the past rather than just the theoretical knowledge. </p>
            <p style={{ paddingTop: "8px" }}>Influenced by the calm but strong colors in the painting ‘The Birth of Venus’ by Sandro Boticelli, by the pastel and dynamic view at Vespa posters we absorbed the aesthetic insights we admire and made an effort to take them to our design process. </p>
            <p style={{ paddingTop: "8px" }}>We mentioned that the coffee is a product of a long journey. The effort and time behind this taste in our glasses coming from far away lands are not always a fact that the consumers are aware of although it constitutes the basis of the pricing. At the same time this journey organically locates the real value of coffee. As this important fact became our focus point we initiated our design process with the ‘idea to remind the consumer of coffee’s story’. The windows we opened on our packages looks to utterly different landscapes through a traveler’s eyes.</p>
            <p style={{ paddingTop: "8px" }}>The countries we buy coffee from have all different texture and landscapes. When we realised the sunsets, beaches, canyons, mountains and roads unique to only one place we reinterpreted the landscapes we loved and we crowned them to these countries we seperated by coding with colors.</p>
            <p style={{ paddingTop: "8px" }}>So as to take the consumer to a sunset in Brasil, to the red earth roads in Kenya or to the vast and warm canyons in Ethiopia, inside these windows we put the landscape illustrations designed in accordance with real photographs belonging to these locations.</p>
            <p style={{ paddingTop: "8px" }}>The box of Acme, were created with an imaginary landscape that we walk through. Contrary to the other illustrations (packages) shaped under day time theme the main difference with this box is that it has a night time look.</p>
            <p style={{ paddingTop: "8px" }}>The last essential phase before the roasted coffee beans are ready for retail is the coffee packages to have up to date info on them. Although the countries we import coffee beans from remain the same, farms and producers in these countries show changes. For this reason the names of the coffee beans are periodically different.</p>
            <p style={{ paddingTop: "8px" }}>As a result of this when we observe the coffee packages in the world market we see a drift to ‘sticker labels’. There happens to be differences in color between sticker labels and main packages produced with totally different printing solutions. This situation affects/changes the ideal outcome on the shelf that the designer and producer willing to see.</p>
            <p style={{ paddingTop: "8px" }}>In order to broaden our borders while looking for the solutions to the production and printing problems, we examined the consumer’s relationship with this variable information at the same time. The fact that the consumer became familiar with the highly variable information like the names of the coffee beans and taste notes have excited us in terms of the development in coffee culture. And we decided that these specific information basically are coffee’s own identity and empowers its story. At this phase we designed the coffee information cards that the consumer can collect and store the info about all and any info about the coffee they ever purchased. We plan to use these information cards that are not stuck on the packages and provide the color and density balance of the design more effectively in the following stages in terms of our marketing strategy.</p>
            <p style={{ paddingTop: "8px" }}>Instead of wasting paper for all the information we need to give about our coffee beans, we have added qr codes to our packages as a digital solution. These qr codes do not only provide up-to-date information, such as the date the coffee beans are roasted. They also refer to our website and sales pages. We also plan to use this advantage for periodical campaigns and surprise events.</p>
        </>
    );
};

export default PetraContent;